language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
gemfile:
  - test/gemfiles/5.0.gemfile
  - test/gemfiles/5.1.gemfile
  - test/gemfiles/5.2.gemfile
before_install:
  - gem update --system
  - gem update bundler
matrix:
  allow_failures:
    - rvm: ruby-head
